name: Notify Main Repo on Push
on:
  push:
    branches: [main]
    
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: nav9v/nav9v.github.io
          event-type: portfolio-updated