name: Sync Portfolio Submodule
on:
  repository_dispatch:
    types: [portfolio-updated]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update submodule
        run: |
          cd portfolio
          git fetch origin
          git reset --hard origin/main || git reset --hard origin/master
          cd ..
          git add portfolio
          
      - name: Commit submodule updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Auto-update portfolio submodule"
          git push
